### PR TITLE
Add PostgreSQL component

### PR DESCRIPTION
**Pull request by bsima**
I basically just copied the H2 component and changed the db spec...

### CODE REVIEW

**Comment by danielsz** [comment]
Thank you very much, @bsima

For the test, you can look at the elasticsearch [test] (https://github.com/danielsz/system/blob/master/test/system/components/elasticsearch_test.clj). 

It is OK for the test to make the assumption that `postgresql` is present on the system. 
Simple operations like detailed [here](https://wiki.postgresql.org/wiki/First_steps) would be great.

**Comment by bsima** [comment]
:+1: I'm gonna wrap this up tonight

**Comment by danielsz** [comment]
Awesome. Thanks!

**Comment by bsima** [comment]
Took me an extra day because somehow my postgres user wasn't setup correctly (I've been using mariadb at work). Anyway, I wrote a test and got it passing. I wasn't sure about the value of additional tests, since all we care about is the connection. I included commented instructions of how to set it up - please let me know if you think this is enough or if I should add more tests, more explanation, or some shell scripts to setup the postgres user automatically :smile: 

shell output:

```sh
system $ lein test system.components.postgres-test  

lein test system.components.postgres-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
```

**Comment by bsima** [comment]
FWIW It's also working in a separate app by monkeypatching the namespace: nebulabio/www@6b5148c

**Comment by danielsz** [comment]
Hi Ben, 

This is looking good. Thanks. Just a couple of things. 

* A shell script creating the user and role would be handy.
* Correct me if I'm wrong, but I think that the database can be created via jdbc instead of depending on a pre-existing one.
* I've seen [a post](http://www.lispcast.com/clojure-database-test-faster) by Eric Norman on database tests, making me wonder if there's any takeaway for us here. Please have a look. I'll trust your judgment.
(I think [this post](http://bobnadler.com/articles/2015/03/04/database-tests-with-rollbacks-in-clojure.html) is related).

Thank you.

**Comment by danielsz** [comment]
The latest `0.1.9-SNAPSHOT` version contains your PR, so you can update your projects with the intended namespaces.
Please let me know if everything works as intended.

**Comment by bsima** [comment]
Okay, I've got some local commits adding some of the things you asked for, I just haven't been able to wrap it up yet. I'll get to it tomorrow or Monday evening at the latest. Thanks!

**Comment by bsima** [comment]
Hey @danielsz, I added a setup script last night. From what I can tell, a database can only be created by a postgres superuser, and so if we are running the test suite on a test user, I don't think we want a test user to be able to create databases as a superuser. Right now the script just creates a standard user.

**Comment by bsima** [comment]
As for the post by Eric Norman, since this is just a single, simple test, I didn't think it would be necessary for the extra scaffolding, tho I did try that method out in an app of my own, it's a pretty cool method.

**Comment by danielsz** [comment]
Thank you, @bsima. 
I'll review this asap.

**Pull request merged**
