### PR TITLE
Support for mount state management library

### PR DESCRIPTION
**Pull request by aroemers**
Initial work on https://github.com/danielsz/system/issues/73

It all compiles, but is untested. Needs more fine-tuning and refinement.

### CODE REVIEW

**Comment by danielsz** [comment]
Oh, great! 

May I ask you to kindly squash those commits into one? 

Thank you, @aroemers!

**Comment by aroemers** [comment]
@danielsz here you go

**Comment by danielsz** [comment]
It looks great, @aroemers . Thank you!

Just a couple of small things. 

1, Some tests fail because they haven't been adjusted to refer the new `common` namespace.
2, `project.clj` has a conflict when merging. Your changes should probably be applied after first rebasing from HEAD.

You've already done so much. If you need assistance at this point, please don't hesitate to say so. I can release a snapshot version after the above is addressed, but for a proper release we'll need to write documentation, tests and a sample project. We can try to recruit some help to facilitate this.

**Comment by danielsz** [comment]
UPDATE: I'm currently looking into the failing tests. I've fixed most of them (really small thing), Mongo is still failing. I need to find some time to investigate properly.

`project.clj` is fixed too.

**Comment by aroemers** [comment]
@danielsz thanks for fixing the tests! If I can help (with my limited time) let me know.

**Comment by danielsz** [comment]
Because there is a couple of additional things that needs to happen before merging in the main branch, I decided to create a dedicated development branch for mount integration based on your work, @aroemers. 

We need to spread the word about this. Anyone that is interested to see mount fully integrated with system is invited to join and contribute.

Thank you!

**Comment by aroemers** [comment]
Hi @danielsz, I guess this PR can be closed?

**Comment by danielsz** [comment]
Thank you for your contribution, @aroemers .

**Pull request closed without merging**
