### PR TITLE
Move doc strings to before argument vector in README

### PR DESCRIPTION
**Pull request by stig**

### CODE REVIEW

**Comment by danielsz** [comment]
Thank you, @stig!

**Comment by stig** [comment]
You're welcome. It seems my main contributions to software these days is minor fixes to READMEs. GitHub makes it so, so simple… :-)

**Comment by danielsz** [comment]
Some days are like that, I suppose (and it's awesome). 
Perfect timing, too, as I was busy improving docstrings and the README :-)

**Comment by stig** [comment]
:cake:

**Pull request merged**
