### PR TITLE
update http-kit, immutant-web and jetty components to define constrai…

### PR DESCRIPTION
**Pull request by brabster**
…nts as type hints and use always-validate metadata to expose better documentation under s/explain and cover more of the API with validation

eg. (s/explain (s/fn-schema new-web-server)) in http-kit namespace says that function returns a WebServer and has three arities with constraints for each.

### CODE REVIEW

**Comment by danielsz** [comment]
Hi @brabster, 

Thank you for this PR. It has an important drawback, though. It reduces the overall readability of the source code as it implies familiarity with Schema's take on type hints. 

It also means using macro extensions by a third party for core features of the language: `defn`, `defrecord` and `fn`. That puts me on alert mode. What if this has unseen consequences (like code reloading, for example).

I am perfectly comfortable calling validation functions from `schema`, but that doesn't mean I want to buy their offerings wholesale, or as one could put it, go `schema` all the way. 

I will leave this PR open for now, and open an issue calling for wider discussion. 

Reference: https://github.com/plumatic/schema#beyond-type-hints

**Comment by danielsz** [comment]
Closing for now. Discussion remains open.

**Comment by brabster** [comment]
Sorry for the lack of activity, started a new job in the last month!

Anyway, I agree with your assessment of the drawbacks. The multiple-arity functions are also troublesome to me, requiring multiple type declarations on each definition to expose schema info to a caller. I think that making the schema available through inspection of the code and via validation errors is a pretty good start.

**Comment by danielsz** [comment]
So we are on the same page! Good luck with your new job :+1:

**Pull request closed without merging**
