### PR TITLE
Fixes #61: Mongo component do not close open connections

### LINKED ISSUE #61: Mongo component do not close open connections
Here is a short tests log from what is visible that Mongo component dereference db variable, but do not close actual connection.

```
11:20:32.141 [cluster-ClusterId{value='56cbcfff4d1a1109e5b7819d', description='null'}-127.0.0.1:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:57}] to 127.0.0.1:27017
...
11:20:32.234 [cluster-ClusterId{value='56cbd0004d1a1109e5b7819e', description='null'}-127.0.0.1:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:58}] to 127.0.0.1:27017
...
11:20:32.269 [main] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:59}] to 127.0.0.1:27017
...
11:20:32.435 [cluster-ClusterId{value='56cbd0004d1a1109e5b7819f', description='null'}-127.0.0.1:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:60}] to 127.0.0.1:27017
...
11:20:32.440 [main] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:61}] to 127.0.0.1:27017
...
11:20:32.470 [cluster-ClusterId{value='56cbd0004d1a1109e5b781a0', description='null'}-127.0.0.1:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:62}] to 127.0.0.1:27017
...
11:20:32.476 [main] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:7, serverValue:63}] to 127.0.0.1:27017
...
11:20:32.501 [cluster-ClusterId{value='56cbd0004d1a1109e5b781a1', description='null'}-127.0.0.1:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:8, serverValue:64}] to 127.0.0.1:27017
...
11:20:32.505 [main] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:9, serverValue:65}] to 127.0.0.1:27017
...
11:20:32.537 [cluster-ClusterId{value='56cbd0004d1a1109e5b781a2', description='null'}-127.0.0.1:27017] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:10, serverValue:66}] to 127.0.0.1:27017
...
11:20:32.541 [main] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:11, serverValue:67}] to 127.0.0.1:27017

Ran 6 tests containing 27 assertions.
0 failures, 0 errors.
```

### PR DESCRIPTION
**Pull request by mBut**

### CODE REVIEW

**Comment by danielsz** [comment]
Excellent, @mBut, thank you so much.

Could you rebase your commit on master. The mongo component you've been working on is not the latest. But I don't think there will be any problem beyond some adjustments.

Thank you!

**Comment by mBut** [comment]
@danielsz for me HEAD history looks fine. I think you confused because of the to big diff. It's because also been added idempotence as described [here](https://github.com/stuartsierra/component#idempotence) and because of `if` wrapper whole block have been shifted. If you will check again you will see that  recently added options still in place. 

Thank you

**Comment by danielsz** [comment]
Yes, that is exactly what happens. Sorry about that. Fantastic. :+1: 

Thanks!

**Comment by danielsz** [comment]
I've pushed a snapshot with those changes.

The main goal of this PR has been achieved: the `mongo` component is now idempotent, and closes its connection when stopped. 

Please note that I've removed the fixture, because I think it is not correct. 

First, I noticed intermittent failures. When those were happening, it was invariably because the initial number of connections was not equal to the current number of connections  (for example, 6 initial connections versus 7 actual connections). 

More importantly, that is perfectly fine. The underlying java driver manages its pool of connections. It is not a user concern as how it does that (beyond providing options like`:connections-per-host`). It is completely normal that at startup, the `server-status` command will report 6 connections, and after doing some operations, it will report 7 current connections. It is inconsequential, and we can't learn anything from that. So this particular test is as far as I can see is redundant. 

Please feel free however to make your case, to propose an alternate test, or to leave it at that.

**Pull request merged**
